# Generated by Django 4.2.5 on 2023-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=25, verbose_name='Nome do artista')),
                ('price', models.FloatField(verbose_name='Valor do ingresso')),
                ('datetime', models.DateTimeField(verbose_name='Data e horário do show')),
                ('description', models.TextField(verbose_name='Descrição do show')),
                ('image', models.ImageField(upload_to='img', verbose_name='Imagem de capa')),
                ('city', models.CharField(choices=[('Itu', 'Itu'), ('Salto', 'Salto'), ('Campinas', 'Campinas')], max_length=15, verbose_name='Cidade')),
                ('neighbourhood', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rua')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
