# Generated by Django 4.2.5 on 2023-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='value',
            new_name='price',
        ),
        migrations.AddField(
            model_name='show',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='city',
            field=models.CharField(default='Itu', max_length=20, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='show',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='show',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rua'),
        ),
    ]
