# Generated by Django 4.2.5 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_rename_value_show_price_show_cep_show_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Cidade'),
        ),
    ]
