# Generated by Django 4.2.3 on 2023-09-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_alter_show_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='city',
            field=models.CharField(choices=[('Itu', 'Itu'), ('Salto', 'Salto'), ('Campinas', 'Salto')], max_length=15, verbose_name='Cidade'),
        ),
    ]
